Reusable modules for EC2, RDS and Network
Debashbora/arc-training-mono-repo-debash pull request #6
Opened 2024-05-27 09:13 UTC by Debashbora

Added Example folder to depict usage of EC2, RDS, and Network modules created earlier:
![Screenshot from 2024-05-27 14-43-10](https://github.com/Debashbora/arc-training-mono-repo-debash/assets/69884255/6a12ac30-f8b1-4191-ae96-d085f4edbb8d)
![Screenshot from 2024-05-27 14-42-37](https://github.com/Debashbora/arc-training-mono-repo-debash/assets/69884255/ddc13ff2-c068-4491-b15e-64a3f72a3a6d)
![Screenshot from 2024-05-27 14-42-28](https://github.com/Debashbora/arc-training-mono-repo-debash/assets/69884255/6e2f992b-a202-4de5-8e93-4a14064813b1)
![Screenshot from 2024-05-27 14-42-20](https://github.com/Debashbora/arc-training-mono-repo-debash/assets/69884255/838e0aa9-85e7-497b-a599-2e80db7305eb)

2024-05-28 07:23 UTC, mayank0202 requested changes
run pre-commit please

2024-05-28 07:23 UTC, mayank0202 commented on terraform/example/ec2/data.tf
> +data "aws_vpc" "poc_vpc" {
fetch ami from data lookups

2024-05-28 07:23 UTC, mayank0202 commented on terraform/example/rds/main.tf
> +}
add tags also

2024-05-28 07:54 UTC, Debashbora commented on terraform/example/rds/main.tf
> +}
done

2024-05-28 07:54 UTC, Debashbora commented on terraform/example/ec2/data.tf
> +data "aws_vpc" "poc_vpc" {
done, Kindly check

2024-05-29 05:14 UTC, mayank0202 reviewed
LGTM

2024-05-29 05:15 UTC, mayank0202 approved these changes
LGTM

2024-05-29 05:39 UTC, merged